output "resource_group_name" {
  description = "Name of the provisioned Azure Resource Group"
  value       = azurerm_resource_group.rg.name
}

output "web_app_name" {
  description = "Name of the provisioned Web App"
  value       = azurerm_linux_web_app.app.name
}

output "web_app_default_hostname" {
  description = "Default FQDN URL generated by Azure"
  value       = azurerm_linux_web_app.app.default_hostname
}